HackCW/HackCW/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('BookStore.urls')),

    path('admin/', admin.site.urls),
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HackCW/BookStore/forms.py
from . import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'USERNAME'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'FIRST NAME'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'LAST NAME'}))

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'EMAIL'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'PASSWORD'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'CONFIRM PASSWORD'}))
    class Meta:
        model=User
        fields = ['username', 'email', 'first_name','last_name','password1', 'password2']


class ProfileForm(forms.ModelForm):
    picture = forms.ImageField()
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ADDRESS'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'CITY'}))
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'STATE'}))
    pincode = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'PINCODE'}))
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'PHONE'}))
    university_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'UNIVERSITY NAME'}))
    class Meta:
        model=models.Profile
        fields = ['picture','address','city','pincode','state','phone','university_name']


class SellBookForm(forms.ModelForm):
    # image = forms.ImageField()
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'BOOK NAME'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'SUBJECT'}))
    price = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'BOOK PRICE'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DESCRIPTION'}))
    college_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'COLLEGE'}))
    book_university = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'UNIVERSITY'}))
    seller_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'OWNER NAME'}))
    seller_email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'OWNER E-MAIL'}) )


    class Meta:
        model=models.SellBook
        fields = ['image','name','subject','price','description','college_name','book_university','seller_name','seller_email']






class ContactUsForm(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    From = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control' , 'placeholder':'Your Email'}))
    Subject=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' , 'placeholder':'Subject'}))
    Message=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' , 'placeholder':'Message'}))
    class Meta:
        model=models.ContactUs
        fields=['username','From','Subject','Message']



x=forms.TextInput(attrs={'class':'form-control'})
class OrderForm(forms.ModelForm):
    name=forms.CharField(widget=x)
    email=forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    phone=forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    address=forms.CharField(widget=x)
    state=forms.CharField(widget=x)
    city=forms.CharField(widget=x)
    postal_zip=forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))

    class Meta:
        model=models.Order
        fields=['name','email','phone','address','state','city','postal_zip']

HackCW/templates/ChangePassword.html
{% extends 'base.html'  %}

{% block body %}
    <!-- Page Content -->
    <div class="page-heading contact-heading header-text" style="background-image: url(https://legaciesandmemoriespublishing.com/images/slides/1.jpg);">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h2>CHANGE PASSWORD</h2>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="send-message">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Change Password</h2>
            </div>
          </div>
          <div class="col-md-8">
            <div class="contact-form">
              <form id="contact"  method="post">
                  {% csrf_token %}
                <div class="row">

                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
<input type="password" name="old_password" class="form-control" autocomplete="current-password" autofocus="" required="" id="id_old_password" placeholder="OLD PASSWORD">                    </fieldset>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <fieldset>
<input type="password" name="new_password1" class="form-control" autocomplete="new-password" required="" id="id_new_password1" placeholder="NEW PASSWORD">                    </fieldset>
                 <ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
<input type="password" name="new_password2" class="form-control" autocomplete="new-password" required="" id="id_new_password2" placeholder="PASSWORD CONFIRM">                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="filled-button" >Change Password</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>

    {% endblock %}

HackCW/templates/about.html
{% extends 'base.html'  %}

{% block body %}



<!-- Page Content -->
    <div class="page-heading about-heading header-text" style="background-image: url(https://www.hampshire.edu/sites/default/files/header_images/herosmall_96.jpg);">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>about us</h4>
              <h2>our company</h2>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Lorem ipsum dolor sit amet consectetur adipisicing</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
                        <img src="https://images.pexels.com/photos/2898170/pexels-photo-2898170.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>Lorem ipsum dolor sit amet.</h4>
    <p>Donate-a-Book is an initiative by Online Books Store to help bridge the gap between those who want to help children read and those who need books for children. Together we will build a Reading India by making storybooks accessible to thousands of children and spread the joy of reading. Pratham Books was founded with the mission of putting “a book in every child’s hand”.              <ul class="social-icons">
                </p><br><br>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

HackCW/templates/cart.html
{% extends 'base.html' %}
{% block cartactive %}active{% endblock %}
{% block cartspan %}<span class="sr-only">(current)</span>{% endblock %}
{% load cart%}

{% block body %}
    <div class="page-heading about-heading header-text" style="background-image: url(https://www.behealthy365.org/wp-content/uploads/2018/07/christin-hume-482925-unsplash-1920x500.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-content">
                        <h2>Cart</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="products call-to-action">
        <div class="container">
            <ul class="list-group list-group-flush">

                <li class="list-group-item">
                    <div class="row">
                        <div class="col-2">
                            <h5><strong>Sno.</strong></h5>
                        </div>

                        <div class="col-2">
                            <h5><strong>Image</strong></h5>
                        </div>

                        <div class="col-2">
                            <h5><strong>Book</strong></h5>
                        </div>

                        <div class="col-2 ">
                            <h5><strong>Price</strong></h5>
                        </div>
                         <div class="col-2 ">
                            <h5><strong>Quantity</strong></h5>
                        </div>
                         <div class="col-2 ">
                            <h5><strong>Total</strong></h5>
                        </div>
                    </div>
                </li>
                {#            Total Length :: {{request.session.cart|length}}#}

                     {% for b in book %}

                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-2">
                                <em>{{forloop.counter}}</em>
                            </div>
                            <div class="col-2">
                                <em><img style="max-width:130px;"  src="{{b.image.url}}" alt="" ></em>
                            </div>

                            <div class="col-2">
                                <em>{{b.name}}</em>
                            </div>
                            <div class="col-2 ">
                                <strong>{{b.price|currency}}</strong>
                            </div>
                                                        <div class="col-2">
                                <strong>{{b|cart_quantity:request.session.cart}}</strong>
                            </div>
                            <div class="col-2">
                                <strong>{{b|price_total:request.session.cart|currency}}</strong>
                            </div>

                        </div>
                    </li>
                {% endfor %}

                <li class="list-group-item">
                    <div class="row">
                        <div class="col-6">
                            <em> Cart Total</em>
                        </div>

                        <div class="col-6 text-right">
                            <strong>{{book|total_cart_price:request.session.cart|currency}}</strong>
                        </div>
                    </div>

                </li>



            </ul>
        <br>
 <div class="m-3 p-3">
{#            <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-outline-info border rounded  col-lg-3 float-right">Check out</a>#}
            <a href="{% url 'checkout' %}" class="btn btn-outline-info border rounded  col-lg-3 float-right">Check out</a>

    </div>








  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
              Check Out Form
          </h5>
          <hr>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="m-2 p-3">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="">Name</label>
                  <input type="text" name="name" id="" class="form-control" placeholder="" aria-describedby="helpId">

                </div>
                 <div class="form-group">
                    <label for="">E-Mail</label>
                    <input type="text" name="email" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>
 <div class="form-group">
                    <label for="">Address</label>
                    <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>
                 <div class="form-group">
                    <label for="">City</label>
                    <input type="text" name="city" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>
                 <div class="form-group">
                    <label for="">State</label>
                    <input type="text" name="state" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div> <div class="form-group">
                    <label for="">Zipcode</label>
                    <input type="text" name="postal_zip" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>
                  <input type="submit" class="btn float-right btn-outline-info col-lg-6" value="Check out">
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>



{% endblock %}

HackCW/templates/donatebook.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<form method="POST">#}
{#    {% csrf_token %}#}
{#    {{ RegisterForm.as_p }}#}
{#    <input type="submit">#}
{##}
{#</form>#}
{#</body>#}
{#</html>#}


{% extends 'base.html' %}
{% block sellbookactive %}active{% endblock %}
{% block sellbookspan %}<span class="sr-only">(current)</span>{% endblock %}
{% block body %}

    <!-- Page Content -->
    <div class="page-heading contact-heading header-text" style="background-image: url(https://blog.newrelic.com/wp-content/uploads/book-reading-outside-background-min.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-content">
                        <h4></h4>
                        <h2>Donate BOOK</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {#    <div class="find-us">#}
    {#      <div class="container">#}
    {#        <div class="row">#}
    {#          <div class="col-md-12">#}
    {#            <div class="section-heading">#}
    {#              <h2>Our Location on Maps</h2>#}
    {#            </div>#}
    {#          </div>#}
    {#          <div class="col-md-8">#}
    {#<!-- How to change your own map point#}
    {#	1. Go to Google Maps#}
    {#	2. Click on your location point#}
    {#	3. Click "Share" and choose "Embed map" tab#}
    {#	4. Copy only URL and paste it within the src="" field below#}
    {#-->#}
    {#            <div id="map">#}
    {#              <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed" width="100%" height="330px" frameborder="0" style="border:0" allowfullscreen></iframe>#}
    {#            </div>#}
    {#          </div>#}
    {#          <div class="col-md-4">#}
    {#            <div class="left-content">#}
    {#              <h4>About our office</h4>#}
    {#              <p>Lorem ipsum dolor sit amet, consectetur adipisic elit. Sed voluptate nihil eumester consectetur similiqu consectetur.<br><br>Lorem ipsum dolor sit amet, consectetur adipisic elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti.</p>#}
    {#              <ul class="social-icons">#}
    {#                <li><a href="#"><i class="fa fa-facebook"></i></a></li>#}
    {#                <li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
    {#                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>#}
    {#                <li><a href="#"><i class="fa fa-behance"></i></a></li>#}
    {#              </ul>#}
    {#            </div>#}
    {#          </div>#}
    {#        </div>#}
    {#      </div>#}
    {#    </div>#}


    <div class="send-message">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>UPLOAD BOOK DETAILS</h2>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="contact-form">
                        <form id="contact" method="post" enctype="multipart/form-data" >
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">

                                    <fieldset>


                                        Book Image:<br>
                                        {{ form.image }}
<br><br><br>

                                        {{ form.name }}
                                        {{ form.subject }}
{#                                        {{ form.price }}#}

                                        <input hidden type="number" name="price" value=0 class="form-control" placeholder="BOOK PRICE" required="" id="id_price">

                                        {{ form.description }}
                                        {{ form.college_name }}
                                        {{ form.book_university }}
                                        {{ form.seller_name }}
                                        {{ form.seller_email }}


                                    </fieldset>







                                </div>


                                <br>  <br>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <button type="submit" id="form-submit" class="filled-button">UPLOAD</button>
                                    </fieldset>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

HackCW/templates/donatebookhistory.html
{% extends 'base.html' %}
{% block historyactive %}active{% endblock %}
{% block historyspan %}<span class="sr-only">(current)</span>{% endblock %}
{% block body %}

    <!-- Page Content -->
    <div class="page-heading about-heading header-text" style="background-image: url(https://www.authorscrib.com/wp-content/uploads/2016/04/header_image-new-2.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-content">
{#                        <h4>Lorem ipsum dolor sit amet</h4>#}
                        <h2>Donate Book History</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="products">
        <div class="container">
            <div class="row">

                {#                {{ book }}<br><br>#}
                {% for b in users  %}

                    <div class="col-md-4">
                        <div class="product-item">
                            <a href=" /p_detail/{{ b.id }}">
                            <img src="{{b.image.url}}" alt=""></a>
                            <div class="down-content">
                                                            <a href=" /p_detail/{{ b.id }}">

                                <h4>{{ b.name }} <small>{{ b.subject }}</small></h4></a>
                                <p>{{ b.description}}</p>
                                <p>college: {{ b.college_name}}</p>
                                <p>University: {{ b.book_university}}</p>
                                <p>Owner: {{ b.seller_name}}</p>
                                <p>Contact: {{ b.seller_email}}</p>




                                <a href="/donatebook/{{ b.id }}" class="btn btn-primary cart">UPDATE</a>
                                <span  class="divpr">
                                <form action="/delete/{{ b.id }}/" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary cart">DELETE</button>
                                </form>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-md-12">
                    {% if users.has_other_pages %}
                        <ul class="pages">
                            {% if users.has_previous %}
                                <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in users.paginator.page_range %}
                                {% if users.number == i %}
                                    <li class="active"><a><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                                {% else %}
                                    <li ><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if users.has_next %}
                                <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}



















{##}
{##}
{##}
{##}
{#{% extends "base.html" %}#}
{##}
{#{% block body %}#}
{#    <div class="container"#}
{#    <table class="table table-borderless>#}
{#        <thead class="border-bottom font-weight-bold">#}
{#        <tr>#}
{#            <td>Book Name</td>#}
{#            <td>Subject</td>#}
{#            <td>Price</td>#}
{#            <td>Description</td>#}
{#            <td>College Name</td>#}
{#            <td>University</td>#}
{#            <td>Seller Name</td>#}
{#            <td>Contact</td>#}
{# </tr>#}
{#        </thead>#}
{#            <td>#}
{#                <a href="{% url 'employee_insert' %}" class="btn btn-outline-success">#}
{#                    <i class="fas fa-plus"></i> Add New#}
{#                </a>#}
{#            </td>#}
{##}
{#        <tbody>#}
{#        {% for b in book %}#}
{#            <tr>#}
{#                <td>{{b.book_name}}</td>#}
{#                <td>{{b.subject}}</td>#}
{#                <td>{{b.price}}</td>#}
{#                <td>{{b.description}}</td>#}
{#                <td>{{b.college_name}}</td>#}
{#                <td>{{b.university_name}}</td>#}
{#                <td>{{b.seller_name}}</td>#}
{#                <td>{{b.contact}}</td>#}
{#                <td>#}
{#
{#                </td>#}
{#            </tr>#}
{#        {% endfor %}#}
{#        </tbody>#}
{#    </table>#}
{##}
{#{% endblock %}#}

HackCW/templates/done.html
{% extends 'base.html'  %}

{% block body %}



<!-- Page Content -->
    <div class="page-heading about-heading header-text" style="background-image: url(https://www.hampshire.edu/sites/default/files/header_images/herosmall_96.jpg);">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>about us</h4>
              <h2>our company</h2>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
                <h2>Your Order is Placed You can check status of your Order in Order Section.</h2>

            </div>
              <a href="{% url 'order' %}"> Click here</a>
          </div>
          <div class="col-md-6">
            <div class="right-image">
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

HackCW/templates/orders.html
{% extends 'base.html' %}


{% block body %}
{% load cart %}
{#{% load custom_filter %}#}
<div class="container" style="padding-top:200px">
   <div class="border rounded p-4 m-4">
        <p class="display-4 pl-4 ml-4">Your Orders</p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Order.id</th>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Date</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th> Delivery Status</th>
                </tr>
            </thead>
            <tbody>
                
                {% for order in orders %}
                <tr>
{#                    <td>{{forloop.counter}}</td>#}
                                    <td>{{order.id}}</td>

                    <td><img style="height: 80px;" class="rounded-circle" src="{{order.book.image.url}}" alt=""></td>
                    <td>{{order.book.name}}</td>
                    <td>{{order.date}}</td>
                    <td>{{order.price|currency}}</td>
                    <td>{{order.quantity}}</td>
                    <td>{{order.quantity|multiply:order.price|currency}}</td>
                    {% if order.status %}
                    <td><small class="badge badge-success">Completed</small></td>
                    {%else%}
                    <td><small class="badge badge-warning">Pending</small></td>
                    {% endif %}
                </tr>

                {% endfor %}
               
            </tbody>

        </table>
       
   </div>
</div>





{% endblock %}

HackCW/templates/placed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

HackCW/templates/sellbook.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<form method="POST">#}
{#    {% csrf_token %}#}
{#    {{ RegisterForm.as_p }}#}
{#    <input type="submit">#}
{##}
{#</form>#}
{#</body>#}
{#</html>#}


{% extends 'base.html' %}
{% block uploadbookactive %}active{% endblock %}
{% block uploadbookspan %}<span class="sr-only">(current)</span>{% endblock %}
{% block body %}

    <!-- Page Content -->
    <div class="page-heading contact-heading header-text" style="background-image: url(https://blog.newrelic.com/wp-content/uploads/book-reading-outside-background-min.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-content">
                        <h4></h4>
                        <h2>SELL BOOK</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="send-message">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>UPLOAD BOOK DETAILS</h2>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="contact-form">
                        <form id="contact" method="post" enctype="multipart/form-data" >
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">

                                    <fieldset>


                                        Book Image:<br>
                                        {{ SellBookForm.image }}
<br><br><br>

                                        {{ SellBookForm.name }}
                                        {{ SellBookForm.subject }}
                                        {{ SellBookForm.price }}
                                        {{ SellBookForm.description }}
                                        {{ SellBookForm.college_name }}
                                        {{ SellBookForm.book_university }}
                                        {{ SellBookForm.seller_name }}
                                        {{ SellBookForm.seller_email }}

                                    </fieldset>







                                </div>


                                <br>  <br>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <button type="submit" id="form-submit" class="filled-button">UPLOAD</button>
                                    </fieldset>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}